HS-1473 Enrich ValueTest with missing test cases
OpenNMS-Cloud/horizon-stream pull request #1033
Opened 2023-04-20 13:41 UTC by FrancescoBuc86

https://opennms.atlassian.net/browse/HS-1473

2023-04-25 14:43 UTC, fooker requested changes

2023-04-25 14:43 UTC, fooker commented on minion/minion-flows/flows-parser/src/test/java/org/opennms/horizon/minion/flows/parser/ValueTest.java
> +        Assert.assertEquals(3, listValue.getValue().size());
Should we also test for the values here?

2023-04-25 14:43 UTC, fooker commented on minion/minion-flows/flows-parser/src/test/java/org/opennms/horizon/minion/flows/parser/ValueTest.java
> +        final List<Field> fields = List.of(field("field1", "field1".getBytes("UTF-8").length), field("field2", "field2".getBytes("UTF-8").length));
Should move `"field1".getBytes("UTF-8")` to a constant as the same value is used as real value below.
Also should use a different length for the second field.
Lastly, should no repeat the field name as value but use something different.

2023-04-25 14:43 UTC, fooker commented on minion/minion-flows/flows-parser/src/test/java/org/opennms/horizon/minion/flows/parser/ValueTest.java
> +        Mockito.when(resolver.lookupTemplate(100)).thenReturn(template);
Is method order relevant? If not, should move the `when()` calls directly below the `mock()` call. Same goes for the fields and the template (maybe even inline?).

2023-04-25 14:43 UTC, fooker commented on minion/minion-flows/flows-parser/src/test/java/org/opennms/horizon/minion/flows/parser/ValueTest.java
> +        Assert.assertEquals(2, listValue.getValue().get(0).size());
Check for values?

2023-04-25 14:43 UTC, fooker commented on minion/minion-flows/flows-parser/src/test/java/org/opennms/horizon/minion/flows/parser/ValueTest.java
> +        Assert.assertEquals(1, listValue.getValue().size());
Add a second instance to the data?

2023-04-25 14:43 UTC, fooker commented on minion/minion-flows/flows-parser/src/test/java/org/opennms/horizon/minion/flows/parser/ValueTest.java
> +                return new OctetArrayValue(name, bytes(buffer, length()));
```suggestion
                return new OctetArrayValue(name, bytes(buffer, length));
```

2023-04-25 14:43 UTC, fooker commented on minion/minion-flows/flows-parser/src/test/java/org/opennms/horizon/minion/flows/parser/ValueTest.java
> +        Assert.assertEquals(2, listValue.getValue().get(0).size());
Same comments as for `testSubTemplateList` apply here, too.

2023-05-02 10:53 UTC, FrancescoBuc86 commented on minion/minion-flows/flows-parser/src/test/java/org/opennms/horizon/minion/flows/parser/ValueTest.java
> +        Assert.assertEquals(3, listValue.getValue().size());
sure

2023-05-02 11:04 UTC, FrancescoBuc86 commented on minion/minion-flows/flows-parser/src/test/java/org/opennms/horizon/minion/flows/parser/ValueTest.java
> +        final List<Field> fields = List.of(field("field1", "field1".getBytes("UTF-8").length), field("field2", "field2".getBytes("UTF-8").length));
ok

2023-05-02 11:14 UTC, FrancescoBuc86 commented on minion/minion-flows/flows-parser/src/test/java/org/opennms/horizon/minion/flows/parser/ValueTest.java
> +        Mockito.when(resolver.lookupTemplate(100)).thenReturn(template);
ok

2023-05-02 11:46 UTC, FrancescoBuc86 commented on minion/minion-flows/flows-parser/src/test/java/org/opennms/horizon/minion/flows/parser/ValueTest.java
> +        Assert.assertEquals(2, listValue.getValue().get(0).size());
sure

2023-05-03 13:33 UTC, FrancescoBuc86 commented on minion/minion-flows/flows-parser/src/test/java/org/opennms/horizon/minion/flows/parser/ValueTest.java
> +        Assert.assertEquals(1, listValue.getValue().size());
sure

2023-05-03 13:33 UTC, FrancescoBuc86 commented on minion/minion-flows/flows-parser/src/test/java/org/opennms/horizon/minion/flows/parser/ValueTest.java
> +        Assert.assertEquals(2, listValue.getValue().get(0).size());
ok

2023-05-03 14:40 UTC, fooker requested changes

2023-05-03 14:40 UTC, fooker commented on minion/minion-flows/flows-parser/src/test/java/org/opennms/horizon/minion/flows/parser/ValueTest.java
> +        Assert.assertEquals(3, listValue.getValue().size());
To improvements:
- You can directly cast to the value returned by `getValue`. Should be pretty stable.
- Split up the values we expect to something like `23 * 0x100 + 42` which would explain why these match.

2023-05-03 14:40 UTC, fooker commented on minion/minion-flows/flows-parser/src/test/java/org/opennms/horizon/minion/flows/parser/ValueTest.java
> +        byte[] field2 = field2Value.getBytes(StandardCharsets.UTF_8);
```suggestion
        byte[] field2Name = "secondField".getBytes();
        byte[] field2Value = "secondFieldValue".getBytes();
```

2023-05-03 14:40 UTC, fooker commented on minion/minion-flows/flows-parser/src/test/java/org/opennms/horizon/minion/flows/parser/ValueTest.java
> +        Mockito.when(resolver.lookupTemplate(100)).thenReturn(Template.builder(100, Template.Type.OPTIONS_TEMPLATE)
Should be a `Template.Type.TEMPLATE`

2023-05-03 14:40 UTC, fooker commented on minion/minion-flows/flows-parser/src/test/java/org/opennms/horizon/minion/flows/parser/ValueTest.java
> +            .writeBytes(field2); // Field 2 list 2
We should add a second template with some more data here.

2023-05-03 15:01 UTC, FrancescoBuc86 commented on minion/minion-flows/flows-parser/src/test/java/org/opennms/horizon/minion/flows/parser/ValueTest.java
> +        Mockito.when(resolver.lookupTemplate(100)).thenReturn(Template.builder(100, Template.Type.OPTIONS_TEMPLATE)
ok

2023-05-04 14:02 UTC, FrancescoBuc86 commented on minion/minion-flows/flows-parser/src/test/java/org/opennms/horizon/minion/flows/parser/ValueTest.java
> +        Assert.assertEquals(3, listValue.getValue().size());
done

2023-05-04 14:38 UTC, fooker commented on minion/minion-flows/flows-parser/src/test/java/org/opennms/horizon/minion/flows/parser/ValueTest.java
> +            .writeBytes(field2); // Field 2 list 2
Can we add a different set of fields to the second template?

2023-05-04 14:40 UTC, fooker commented on minion/minion-flows/flows-parser/src/test/java/org/opennms/horizon/minion/flows/parser/ValueTest.java
> +        Assert.assertEquals(3, listValue.getValue().size());
That's the way the values is build from the values we write in the raw bytes.

2023-05-05 11:44 UTC, FrancescoBuc86 commented on minion/minion-flows/flows-parser/src/test/java/org/opennms/horizon/minion/flows/parser/ValueTest.java
> +            .writeBytes(field2); // Field 2 list 2
yep, updated

2023-05-08 08:14 UTC, merged