HS-1490 - Using schemas instead of dbs for services works. Have ignor…
OpenNMS-Cloud/horizon-stream pull request #1035
Opened 2023-04-20 17:19 UTC by jaymberry

…ed grafana

## Description
Put db services into different schemas in single db.

## Jira link(s)
- https://issues.opennms.org/browse/HS-1490 

## Flagged for review

## Checklist
* [ ] Follows Horizon Stream's [development guidelines.](https://github.com/OpenNMS/horizon-stream/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS/horizon-stream/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.
* [ ] Notify devops of changes to the Charts

2023-04-20 17:44 UTC, geraldhumphries requested changes

2023-04-20 17:44 UTC, geraldhumphries commented on charts/opennms/templates/postgres/postgres-init-secret.yaml
> +    GRANT ALL ON DATABASE horizon_stream TO keycloak;
No need to `GRANT ALL` here, `CREATE SCHEMA IF NOT EXISTS keycloak AUTHORIZATION keycloak;` will give the role all the permissions it needs by making it the owner of the schema. It'll also protect against services accessing the wrong schemas.

2023-04-20 17:44 UTC, geraldhumphries commented on charts/opennms/templates/opennms/inventory/inventory-deployment.yaml
> +              #value: "jdbc:postgresql://postgres:5432/inventory"
nit: leftover comment

2023-04-21 20:24 UTC, jaymberry commented on charts/opennms/templates/postgres/postgres-init-secret.yaml
> +    GRANT ALL ON DATABASE horizon_stream TO keycloak;
Removed these

2023-04-21 20:25 UTC, jaymberry commented on charts/opennms/templates/opennms/inventory/inventory-deployment.yaml
> +              #value: "jdbc:postgresql://postgres:5432/inventory"
Strange, it is removed in the code, but the PR keeps showing it as there. Should be removed.

2023-05-01 14:18 UTC, geraldhumphries commented on charts/opennms/templates/keycloak/keycloak-deployment.yaml
> +              value: "{{ .Values.Postgres.DbSchemaName }}"
Should these be under `.Values.Keycloak...`?

2023-05-01 15:24 UTC, jaymberry commented on charts/opennms/templates/keycloak/keycloak-deployment.yaml
> +              value: "{{ .Values.Postgres.DbSchemaName }}"
Updated

2023-05-01 15:37 UTC, geraldhumphries approved these changes

2023-05-01 15:50 UTC, merged