Jira/hs 1464 pageobjects
OpenNMS-Cloud/horizon-stream pull request #1044
Opened 2023-04-21 17:47 UTC by chuklov

## Description
Page object for Appliance page

## Jira link(s)
- https://issues.opennms.org/browse/HS-1464

2023-04-23 00:32 UTC, bahka requested changes

2023-04-23 00:32 UTC, bahka commented on external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/pages/cloud/AppliancePage.java
> +        deviceNameInput.sendKeys(name);
usually I add .shouldBe(enabled) for all actions (before sendKeys, click, etc) - to be sure that it's not disabled (it checks it visible and enabled and wait this state for 4 seconds by default).

2023-04-23 00:32 UTC, bahka commented on external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/pages/cloud/AppliancePage.java
> +    public static void setDeviceIpInput(String ipAddress) {
`setDeviceIp` I suppose Input is extra here

2023-04-23 00:32 UTC, bahka commented on external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/pages/cloud/AppliancePage.java
> +    public static void clickAddDevice() {
you have some method with `button` and some without. so it's better to use the same naming patter

2023-04-23 00:32 UTC, bahka commented on external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/pages/cloud/AppliancePage.java
> +    public static boolean checkIsAddDeviceButtonVisible() {
I prefer keep selenide check instead of assert, since selenide one does screenshots.

also, isDisplayed - is a current status, when you use `shouldBe(x)` it waits up to 4 seconds, it's nice since UI works not so fast .

2023-04-23 00:32 UTC, bahka commented on external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/pages/cloud/AppliancePage.java
> +package org.opennms.horizon.systemtests.pages.cloud;
copyrights (c)

2023-04-23 00:32 UTC, bahka commented on external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/pages/cloud/ConfirmDeleteMinionPopup.java
> +package org.opennms.horizon.systemtests.pages.cloud;
copyrights (c)

2023-04-23 00:32 UTC, bahka commented on external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/steps/cloud/ApplianceSteps.java
> +            if (!$(byText(minionName.toUpperCase())).isDisplayed()) {
it's already should be upper case in MINIONS.

2023-04-23 00:32 UTC, bahka commented on external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/steps/cloud/ApplianceSteps.java
> +        if (minionName.equals("DEFAULT")) {
I do we have another cases? If we operate only by default minion we can simplify it with hidden minion name.

also we have `TestDataStorage` class where we can add a method : mapMinionName(minionName) to avoid this condition check in different steps. (the same as emails)

2023-04-23 00:32 UTC, bahka commented on external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/steps/cloud/ApplianceSteps.java
> +        Selenide.sleep(count * 30_000);
I just have thoughts that we should do that by API call, later

2023-04-23 00:32 UTC, bahka commented on external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/steps/cloud/ApplianceSteps.java
> +    @Then("check that the remove Minion button is displayed")
I suppose it's `delete` button. 
Also I don't think that it make sense to check it's visibility  (the only visibility `isDisplayed`) and action in 2 different steps.  I prefer just functional style - we verify that some element is visible by acting with it (click, set, get text...) 

when you do `click` on element if you use `shouldBe(enabled)` it will be automatically checked.

2023-04-23 00:32 UTC, bahka commented on external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/steps/cloud/ApplianceSteps.java
> +    @Then("click on the delete button for minion")
the button name I set in ' ' even if it's just icon button.

2023-04-23 00:32 UTC, bahka commented on external-it/hs-system-tests/src/test/resources/cloud-features/appliance-tests.feature
> +    Then check 'Add Device' button is accessible and visible
just click on this button (use .shouldBe(enabled) to verify visibility and accessibility) for all that cases when we check visibility and then act with the field in 2 steps

2023-04-23 00:32 UTC, bahka commented on external-it/hs-system-tests/src/test/resources/cloud-features/appliance-tests.feature
> +    Then click on 'Add Device' button to open a pop up window
do we need this part `to open a pop up window`? 

I add another step for such case:

> Then `name` popup appear 

(to wait when this popup will appear) also I have the opposite case to check validation case (when popup isn't closed)

2023-04-23 00:32 UTC, bahka commented on external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/steps/cloud/ApplianceSteps.java
> +    @Then("fill details of a newly added device with name {string} and ip address {string}")
do you consider to have more atomic steps 

@Then("set device name as {string}")
@Then("set device ip as {string}")
@Then("click 'SAVE' button")

2023-04-23 00:32 UTC, bahka commented on external-it/hs-system-tests/src/test/resources/cloud-features/appliance-tests.feature
> +    Then check the status of the minion is "UP"
I assume it worth to add a step to verify that we don't have this 'delete' button when it's UP

2023-04-24 17:05 UTC, chuklov commented on external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/steps/cloud/ApplianceSteps.java
> +    @Then("check that the remove Minion button is displayed")
This is different functionality. The button should be visible only in case the minion is inactive. At this step, I'm not interacting with it. I'm checking the functionality of the button visibility.

2023-04-24 17:10 UTC, chuklov commented on external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/pages/cloud/AppliancePage.java
> +    public static boolean checkIsAddDeviceButtonVisible() {
isDisplayer returns false or true while shouldBe(x) crashes in case the element is not displayed.

2023-04-24 20:17 UTC, bahka approved these changes
LGTM

2023-04-24 20:17 UTC, bahka commented on external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/pages/cloud/AppliancePage.java
> +        deviceNameInput.shouldBe(visible, enabled).sendKeys(name);
`enable` is enough, it's a mix of `visible` and `clickable`

2023-04-24 20:17 UTC, bahka commented on external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/pages/cloud/AppliancePage.java
> +        deviceNameInput.shouldBe(visible, enabled).sendKeys(name);
FYI: all inputs are working in that way:

sendKeys - adds the text to existed text. (I suppose UI decided that)

In case if you want to change text in that input you need to use :
.setValue("").sendKeys(txt) 

if not - it's ok as is. (it make sense when you check validation cases)

2023-04-24 20:26 UTC, merged