HS-1132: Passive discovery validations
OpenNMS-Cloud/horizon-stream pull request #1063
Opened 2023-04-26 13:17 UTC by rabzobi

## Description
Allow update to keep the same location
Validate community string according to rules in ticket

## Jira link(s)
- https://issues.opennms.org/browse/HS-1132

## Flagged for review
Not sure of validation requirement for community strings and comma's. I have implemented as per my understanding from the ticket.

## Checklist
* [X] Follows Horizon Stream's [development guidelines.](https://github.com/OpenNMS/horizon-stream/wiki/Development-Guidelines)
* [X] Appropriate reviewer(s) have been selected.
* [X] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS/horizon-stream/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.
* [ ] Notify devops of changes to the Charts

2023-04-28 13:31 UTC, james8hut requested changes
Any JUnit tests?

2023-04-28 13:33 UTC, james8hut commented on inventory/main/src/main/java/org/opennms/horizon/inventory/service/discovery/PassiveDiscoveryService.java
> +            snmpCommunities += snmpCommunity.replace(",","") + " "; // As be requirement on HS-1332
I'm not sure what the comment means exactly.
I'd also be inclined to remove it anyway.

2023-04-28 14:24 UTC, rabzobi commented on inventory/main/src/main/java/org/opennms/horizon/inventory/service/discovery/PassiveDiscoveryService.java
> +            snmpCommunities += snmpCommunity.replace(",","") + " "; // As be requirement on HS-1332
It was supposed to say "as per"... but I have removed it

2023-05-02 15:57 UTC, rabzobi commented
> Any JUnit tests?

I have added some tests

2023-05-03 08:57 UTC, james8hut requested changes

2023-05-03 08:57 UTC, james8hut commented on inventory/main/src/test/java/org/opennms/horizon/inventory/service/PassiveDiscoveryServiceTest.java
> +        assertTrue(exception.getMessage().equals("Snmp communities string is too long"));
I would create a separate test method for each of these things. If the too long test fails then the 7 bit ascii test doesn't get to run, so I always find it annoying as a developer, if I was to fix the too long test, and only then find out the 7 bit ascii test was going to fail as well.

2023-05-03 08:57 UTC, james8hut commented on inventory/main/src/main/java/org/opennms/horizon/inventory/service/discovery/PassiveDiscoveryService.java
> +            validateDiscovery(tenantId, request);
Can you add a test to ensure validateDiscovery method isn't called.
Plan to do this:
Comment out the if statement
Test should validateDiscovery and throw an exception. (And fail)
Uncomment the if statement
Test now should pass, as it doesn't call validateDiscovery.

2023-05-03 12:40 UTC, rabzobi commented on inventory/main/src/main/java/org/opennms/horizon/inventory/service/discovery/PassiveDiscoveryService.java
> +            validateDiscovery(tenantId, request);
I've added two heavily mocked test cases which cover the exception scenario (and no exception scenario)

2023-05-03 12:45 UTC, rabzobi commented on inventory/main/src/test/java/org/opennms/horizon/inventory/service/PassiveDiscoveryServiceTest.java
> +        assertTrue(exception.getMessage().equals("Snmp communities string is too long"));
I have moved them all into separate test methods

2023-05-04 12:15 UTC, james8hut approved these changes

2023-05-04 12:21 UTC, merged