HS-1317: Send node from inventory to alerts on create/update
OpenNMS-Cloud/horizon-stream pull request #1090
Opened 2023-05-04 13:26 UTC by james8hut

## Description
Send node to alerts from inventory so node label is available for alerts list.

## Jira link(s)
- https://issues.opennms.org/browse/HS-1317

## Flagged for review
n/a

## Checklist
* [ ] Follows Horizon Stream's [development guidelines.](https://github.com/OpenNMS/horizon-stream/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS/horizon-stream/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.
* [ ] Notify devops of changes to the Charts

2023-05-05 14:25 UTC, rabzobi requested changes
Just switch the debugger off and I think a review from Thomas

2023-05-05 14:25 UTC, rabzobi commented on inventory/docker-it/src/test/java/org/opennms/horizon/inventory/cucumber/CucumberRunnerIT.java
> -        startApplicationContainer(false);   // DEBUGGING - set to true to expose the application debugging on host port 5005
Maybe switch this off

2023-05-09 09:44 UTC, thomasbigger584 approved these changes

2023-05-09 09:55 UTC, rabzobi approved these changes
LGTM

2023-05-09 09:58 UTC, merged