HS-1247 NetflowV5 doesn't have  tag
OpenNMS-Cloud/horizon-stream pull request #1115
Opened 2023-05-11 13:03 UTC by FrancescoBuc86

https://opennms.atlassian.net/browse/HS-1247

2023-05-12 01:43 UTC, freddy61025 commented on metrics-processor/flows/src/main/java/org/opennms/horizon/flows/processing/DocumentEnricherImpl.java
> +                TextFormat.merge(flow.toString(), document);
I believe it is will not solve the problem.
May be the problem is because we should not use 0 for V5. Where 0 is always default value for protobuf. So when persist to ingester flowDoc.toString() it will skip that value due to protobuf think value is not set yet.

FYI:
FlowDocument.class line: 2478 (FlowDocument.newBuilder(flow))
                if (other.netflowVersion_ != 0) {
                    this.setNetflowVersionValue(other.getNetflowVersionValue());
                }

In protobuf.

enum NetflowVersion {
    V5 = 0;
    V9 = 1;
    IPFIX = 2;
    SFLOW = 3;
}

2023-05-12 08:46 UTC, FrancescoBuc86 commented on metrics-processor/flows/src/main/java/org/opennms/horizon/flows/processing/DocumentEnricherImpl.java
> +                TextFormat.merge(flow.toString(), document);
good point

2023-05-12 08:56 UTC, FrancescoBuc86 commented on metrics-processor/flows/src/main/java/org/opennms/horizon/flows/processing/DocumentEnricherImpl.java
> +                TextFormat.merge(flow.toString(), document);
But if this is the problem, why netflowVersion is missing for V9 and IPFix?

2023-05-12 13:19 UTC, freddy61025 requested changes

2023-05-12 13:19 UTC, freddy61025 commented on shared-lib/flows/src/main/proto/flow_document.proto
> +    NONE = 0;
I think it is better to use the same word either all NONE or UNDEFINED.

2023-05-12 13:24 UTC, freddy61025 commented
Make sure to notify DevOps and testers that existing data will be wrong once it is merged.

2023-05-15 13:34 UTC, freddy61025 approved these changes

2023-05-16 10:21 UTC, merged