HS-1474: Refactor charts to allow for global environment variables and Kafka credential secrets
OpenNMS-Cloud/horizon-stream pull request #1152
Opened 2023-05-18 14:26 UTC by geraldhumphries

## Description

- Adds the ability to define "global" environment variables, which are added to any deployments that use spring-boot-env configmap.
- Adds ability to reference a "kafka credentials" secret by name and apply its environment variables.

## Jira link(s)
- https://issues.opennms.org/browse/HS-1474

## Flagged for review

## Checklist
* [ ] Follows Horizon Stream's [development guidelines.](https://github.com/OpenNMS/horizon-stream/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS/horizon-stream/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.
* [ ] Notify devops of changes to the Charts

2023-05-19 14:35 UTC, deejgregor requested changes

2023-05-19 14:35 UTC, deejgregor commented on charts/opennms/templates/opennms/minion/minion-gateway-deployment.yaml
> +          {{- include "kafkaSecretFrom" .Values.OpenNMS.MetricsProcessor | indent 10 }}
s/MetricsProcessor/MinionGateway/

2023-05-19 14:35 UTC, deejgregor commented on charts/opennms/values.yaml
> +    eventHubs:
I don’t see `eventhubs` used anywhere.

2023-05-19 14:35 UTC, deejgregor commented on charts/opennms/templates/opennms/spring-boot-env-configmap.yaml
> +{{- with .Values.OpenNMS.global.openTelemetry }}
Are we using OpenNMS.global.openTelemetry.env or OpenNMS.global.env?

2023-05-19 14:35 UTC, deejgregor commented on charts/opennms/templates/keycloak/keycloak-deployment.yaml
> +            {{- if .Values.OpenNMS.global.env }}
Are we using OpenNMS.global.openTelemetry.env or OpenNMS.global.env?

2023-05-23 16:31 UTC, geraldhumphries commented on charts/opennms/templates/opennms/spring-boot-env-configmap.yaml
> +{{- with .Values.OpenNMS.global.openTelemetry }}
Decided to separate `OpenNMS.global.openTelemetry.env` and `OpenNMS.global.springBoot.env` instead of a single `global.env`. These issues should be fixed now.

2023-05-23 16:32 UTC, geraldhumphries commented on charts/opennms/templates/keycloak/keycloak-deployment.yaml
> +            {{- if .Values.OpenNMS.global.env }}
Answered elsewhere but we are using `OpenNMS.global.openTelemetry.env`.

2023-05-24 15:16 UTC, deejgregor commented on charts/opennms/templates/opennms/spring-boot-eventhubs-env-secret.yaml
> +  name: spring-boot-eventhubs-credentials
I don't think you want to commit this. ;-)

2023-05-24 15:36 UTC, geraldhumphries commented
> Remove the [charts/opennms/templates/opennms/spring-boot-eventhubs-env-secret.yaml](https://github.com/OpenNMS-Cloud/horizon-stream/pull/1152/files#diff-ac1277f7baf99671e78110cbeb68513c9ac896bc305ee5a2c72764b44443d2d2) that looks like it was accidentally committed. And change passwords. :)

Ouch. Key revoked and the secret is gone.

2023-05-24 16:36 UTC, merged