Update README
OpenNMS-Cloud/horizon-stream pull request #270
Opened 2022-09-02 16:49 UTC by indigo423

Adding some more detailed information on what the project goal is and providing some very basic about the license, where to find help, and documentation.

## Jira link(s)
https://issues.opennms.org/browse/HS-302

## Checklist
* [ ] Follows Horizon Stream's [development guidelines.](https://github.com/OpenNMS/horizon-stream/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS/horizon-stream/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.

2022-09-02 20:28 UTC, Bonrob2 requested changes
A few updates and comments on the messaging.

2022-09-02 20:28 UTC, Bonrob2 commented on README.md
> +Horizon Stream is the future of OpenNMS Horizon, an open source network monitoring.
```suggestion
Horizon Stream is the future of OpenNMS Horizon, an open source network monitoring platform.
```

2022-09-02 20:28 UTC, Bonrob2 commented on README.md
> +☣️ The project is in a very early stage and things break and move around. It is not ready to run production workloads.
```suggestion
☣️ The project is in a very early stage and things break and move around.
It is not ready to run production workloads.
```

2022-09-02 20:28 UTC, Bonrob2 commented on README.md
> +As it is right now you need a K8s cluster with 24GB RAM.
```suggestion
Currently you need a K8s cluster with 24GB RAM.
```

2022-09-02 20:28 UTC, Bonrob2 commented on README.md
> +We use the GitHub Wiki in the Horizon Stream GitHub project for documentation of the project.
```suggestion
We use the GitHub Wiki in the Horizon Stream GitHub project to document the project.
```

2022-09-02 20:28 UTC, Bonrob2 commented on README.md
> +You find the documentation how to get it installed in the [administrators getting started](https://github.com/OpenNMS/horizon-stream/wiki/Getting-Started---Admin) section.
```suggestion
The following sections might be of most interest: 
* Installation in the [administrators getting started](https://github.com/OpenNMS/horizon-stream/wiki/Getting-Started---Admin) section.
```

2022-09-02 20:28 UTC, Bonrob2 commented on README.md
> +If you are interested in building it from source you find instruction in our [developers getting started](https://github.com/OpenNMS/horizon-stream/wiki/Getting-Started) chapter.
```suggestion
* Building from source  in the [developers getting started](https://github.com/OpenNMS/horizon-stream/wiki/Getting-Started) section.
```

2022-09-02 20:28 UTC, Bonrob2 commented on README.md
> +In case you want to contribute code you can find instructions in our [contribution guidelines](https://github.com/OpenNMS/horizon-stream/wiki/Development-Guidelines).
```suggestion
* [Contribution guidelines](https://github.com/OpenNMS/horizon-stream/wiki/Development-Guidelines), if you want to contribute code.
```

2022-09-02 20:28 UTC, Bonrob2 commented on README.md
> +In case you run into problems, you can look into [troubleshooting](https://github.com/OpenNMS/horizon-stream/wiki/Troubleshooting) for quick help.
```suggestion
* [Troubleshooting](https://github.com/OpenNMS/horizon-stream/wiki/Troubleshooting) for quick help.
```

2022-09-02 20:28 UTC, Bonrob2 commented on README.md
> +We know people in the OpenNMS community and commercial customers spent time and money to integrate OpenNMS Horizon into their environments. OpenNMS Horizon gets the maintenance and enhancements throu
```suggestion
We know people in the OpenNMS community and commercial customers spent time and money to integrate OpenNMS Horizon into their environments.
OpenNMS Horizon gets the maintenance and enhancements through the OpenNMS Plugin API extensions without a change.
```

2022-09-02 20:28 UTC, Bonrob2 commented on README.md
> +# Horizon Stream 🚀
Need to determine if stream is the name we are going to use even at this early stage. That is a marketing call.

2022-09-02 20:28 UTC, Bonrob2 commented on README.md
> +It aims to be an easy to use, secure, reliable and extensible open-source network monitoring plattform.
These two lines require a bit of messaging. They imply that Horizon doesn't already give them this. How can we position Stream effectively?

2022-09-02 20:28 UTC, Bonrob2 commented on README.md
> +To get these principles addressed without breaking people's current solutions and implementations.
What principles are we addressing?

2022-09-02 20:28 UTC, Bonrob2 commented on README.md
> +We know people in the OpenNMS community and commercial customers spent time and money to integrate OpenNMS Horizon into their environments. OpenNMS Horizon gets the maintenance and enhancements throu
Also, what maintenance and enhancements? From Stream?

2022-09-02 20:28 UTC, Bonrob2 commented on README.md
> +We can't do a major re-architecture of the platform without breaking things for our current users.
It is not clear from earlier that we are doing a re-architecture of the platform. Suggest being clear about that near the beginning.

2022-09-02 20:28 UTC, Bonrob2 commented on README.md
> +Our goal is to take over the OpenNMS Plugin API as an integration contract, and we aim to make the existing plugins compatible.
```suggestion
Our goal is to take over the OpenNMS Plugin API as an integration contract, and we aim to make the existing plugins compatible.
```
Integration with Horizon?

2023-01-12 19:14 UTC, j-white commented
@indigo423 what's the next step here?

2023-03-29 12:41 UTC, closed without merging