Use test containers instead of docker-maven-plugin for Minion docker-it.
OpenNMS-Cloud/horizon-stream pull request #656
Opened 2023-01-23 22:39 UTC by artnaseef

## Description

## Jira link(s)
- https://issues.opennms.org/browse/HS-xx

## Flagged for review

## Checklist
* [ ] Follows Horizon Stream's [development guidelines.](https://github.com/OpenNMS/horizon-stream/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS/horizon-stream/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.

2023-01-23 23:16 UTC, geraldhumphries requested changes

2023-01-23 23:16 UTC, geraldhumphries commented on minion/docker-it/src/test/java/org/opennms/horizon/dockerit/testcontainers/TestContainerRunnerClassRule.java
> +    private void startZookeeperContainer() {
Method name still refers to Zookeeper, how about `startMockMinionGatewayContainer`?

2023-01-23 23:27 UTC, artnaseef commented on minion/docker-it/src/test/java/org/opennms/horizon/dockerit/testcontainers/TestContainerRunnerClassRule.java
> +    private void startZookeeperContainer() {
Good catch.  Fixing.

2023-01-24 15:48 UTC, geraldhumphries approved these changes

2023-01-24 18:06 UTC, merged