HS-863: Deletion of nodes should remove tasksets
OpenNMS-Cloud/horizon-stream pull request #682
Opened 2023-01-30 23:59 UTC by cgorantla

## Description

Deletion of nodes should remove tasksets, some cleanup on Tasksets.

## Jira link(s)
- https://issues.opennms.org/browse/HS-863

## Flagged for review

## Checklist
* [ ] Follows Horizon Stream's [development guidelines.](https://github.com/OpenNMS/horizon-stream/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS/horizon-stream/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.

2023-02-02 21:37 UTC, yangli2014 commented on inventory/src/main/java/org/opennms/horizon/inventory/model/IpInterface.java
> +
Is this change related to this Jira story?

2023-02-02 21:48 UTC, cgorantla commented on inventory/src/main/java/org/opennms/horizon/inventory/model/IpInterface.java
> +
yes, I need to derive monitor/collectors currently running on Minion, for that I need to know which services are running on a given Interface.

2023-02-02 22:03 UTC, splatch requested changes
We have one file which needs to be removed. Beyond that it looks good.

2023-02-02 22:03 UTC, splatch commented on inventory/src/main/java/org/opennms/horizon/inventory/service/taskset/publisher/GrpcTaskSetPublisher.java
> +        if (existingTaskSet != null) {
Can existing taskset be null if we i.e. remove node after start, before tasksets were published?

2023-02-02 22:14 UTC, yangli2014 commented on inventory/src/main/java/org/opennms/horizon/inventory/service/NodeService.java
> +    public List<TaskDefinition> getTasksForNode(Node node) {
We should include the node scan task as well.

2023-02-02 23:16 UTC, cgorantla commented on inventory/src/main/java/org/opennms/horizon/inventory/service/NodeService.java
> +    public List<TaskDefinition> getTasksForNode(Node node) {
sure, will do that in different issue ( need to take care of Azure node) as well

2023-02-02 23:41 UTC, cgorantla commented on inventory/src/main/java/org/opennms/horizon/inventory/service/taskset/publisher/GrpcTaskSetPublisher.java
> +        if (existingTaskSet != null) {
yeah, may be very rare. Just taking care before fetching it's children

2023-02-03 17:54 UTC, artnaseef reviewed
I'm going to reach out to discuss some things here in person.

2023-02-03 18:30 UTC, cgorantla commented on inventory/src/main/java/org/opennms/horizon/inventory/service/taskset/CollectorTaskSetUtils.java
> +    public static TaskDefinition getCollectorTask(MonitorType monitorType, IpInterface ipInterface, long nodeId) {
My intention is to remove separate class for each TaskSet creation. Just utilize taskset creation as simple util class. That's why I created TaskSetHandler

2023-02-03 18:30 UTC, cgorantla commented on inventory/src/main/java/org/opennms/horizon/inventory/service/taskset/CollectorTaskSetUtils.java
> +    static TaskDefinition addAzureCollectorTask(AzureCredential credential, AzureScanItem scanItem, String ipAddress, long nodeId) {
default are useful when we want to do unit testing on them and they only need to be exposed to package here.

2023-02-03 18:30 UTC, cgorantla commented on inventory/src/main/java/org/opennms/horizon/inventory/service/taskset/publisher/GrpcTaskSetPublisher.java
>      public synchronized void publishNewTasks(String tenantId, String location, List<TaskDefinition> taskList) {
This is definitely on my mind, `taskSetsByTenantLocation` is the shared data structure here.
This can be removed once we have incremental updates working.

2023-02-03 18:30 UTC, cgorantla commented on inventory/src/test/java/org/opennms/horizon/inventory/grpc/taskset/TestTaskSetGrpcService.java
> +    public synchronized void publishTaskSet(PublishTaskSetRequest request,
This is just a MockTaskSetService, will update

2023-02-08 01:30 UTC, cgorantla commented on inventory/src/test/java/org/opennms/horizon/inventory/service/taskset/publisher/TaskSetPublisherTest.java
> +public class TaskSetPublisherTest {
this is just publisher taskset for removal/add, not testing anything related to Grpc, so it seems fine

2023-02-08 11:52 UTC, thomasbigger584 commented on inventory/src/test/java/org/opennms/horizon/inventory/grpc/AzureCredentialGrpcItTest.java
Where in this test class is mockito being used?

2023-02-08 19:37 UTC, splatch approved these changes
Its good from my side, eventual test updates or unification of policies across projects we can align in separate task.

2023-02-08 19:43 UTC, merged