HS-572 Tilt build error with submodule
OpenNMS-Cloud/horizon-stream pull request #697
Opened 2023-02-06 15:29 UTC by chinh-cle

## Description

## Jira link(s)
- https://issues.opennms.org/browse/HS-572-tilt-multimodule

## Flagged for review

## Checklist
* [ ] Follows Horizon Stream's [development guidelines.](https://github.com/OpenNMS/horizon-stream/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS/horizon-stream/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.

2023-02-13 16:05 UTC, geraldhumphries commented on Tiltfile
> +    if submodule:
Unfortunately this isn't a good way to check if it's a multimodule build, it can be empty for multimodule projects. You might need to use separate `jib_project` and `jib_project_multimodule` functions, and choose which one to use for each project.

2023-02-13 16:06 UTC, geraldhumphries commented on Tiltfile
> +        k8s_resource(
This can be moved inside the multi_module_build function

2023-02-23 13:43 UTC, chinh-cle commented on Tiltfile
> +            sync('{}{}/src/main/resources'.format(base_path, ''), '/app/resources'),
removing the empty string seems to cause the error `Error in format: format: tuple index out of range`
```
Loading Tiltfile at: /Users/cle/dev/horizon-stream/Tiltfile
Running: helm template chart /Users/cle/dev/horizon-stream/charts/opennms --include-crds --values ./tilt-helm-values.yaml
Traceback (most recent call last):
  /Users/cle/dev/horizon-stream/Tiltfile:132:12: in <toplevel>
  /Users/cle/dev/horizon-stream/Tiltfile:60:42: in jib_project
Error in format: format: tuple index out of range
```

2023-02-23 19:21 UTC, geraldhumphries commented on Tiltfile
> +            sync('{}{}/src/main/resources'.format(base_path, ''), '/app/resources'),
You also need to remove one of the `{}` in the string, I think it's complaining about that.

2023-02-23 19:22 UTC, geraldhumphries commented on Tiltfile
> +        deps=['{}/src'.format(base_path, ''), '{}/pom.xml'.format(base_path, '')],
Why pass in empty strings here? There's only one placeholder (the `{}`) so it should only need one argument.

2023-02-24 21:56 UTC, geraldhumphries requested changes
Looking really good, I think it's almost ready

2023-02-24 21:56 UTC, geraldhumphries commented on Tiltfile
> +        'mvn compile -f {} -am {}'.format(base_path, ''),
One more place with an empty string here

2023-02-24 21:56 UTC, geraldhumphries commented on Tiltfile
> +    submodule_flag = '-pl {}'.format(submodule)
This should check if the variable has a value, like the old code. Most (all?) of our multimodule maven projects now allow you to run the Jib plugin at the root, without specifying a submodule. There may actually be no need to use the submodule flag at all!

2023-02-24 21:56 UTC, geraldhumphries commented on Tiltfile
> +jib_project_multi_module(
Here's the list of multimodule projects that should use this function:

- events
- inventory (this is new, after a PR from @artnaseef)
- metrics-processor
- minion-gateway
- minion-gateway-grpc-proxy

Minion is also multimodule, but its image isn't built with Jib so it should not use the function.

2023-02-24 21:56 UTC, geraldhumphries commented on Tiltfile
> +def build_single_module(image_name, base_path):
There's no need to split this off into its own function right now. We could just include the custom_build calls from `build_single_module` and `build_multi_module` in the `jib_project` and `jib_project_multi_module` functions.

2023-02-25 21:14 UTC, chinh-cle commented on Tiltfile
> +jib_project_multi_module(
build as multi module errors:
`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.10.1:compile (default-compile) on project main: Compilation failure: Compilation failure: 
[ERROR] /Users/cle/dev/horizon-stream/metrics-processor/main/src/main/java/org/opennms/horizon/flows/FlowsApplicationConfig.java:[34,48] package org.opennms.horizon.flows.classification does not exist
[ERROR] /Users/cle/dev/horizon-stream/metrics-processor/main/src/main/java/org/opennms/horizon/flows/FlowsApplicationConfig.java:[35,48] package org.opennms.horizon.flows.classification does not exist
[ERROR] /Users/cle/dev/horizon-stream/metrics-processor/main/src/main/java/org/opennms/horizon/flows/FlowsApplicationConfig.java:[36,48] package org.opennms.horizon.flows.classification does not exist
[ERROR] /Users/cle/dev/horizon-stream/metrics-processor/main/src/main/java/org/opennms/horizon/flows/FlowsApplicationConfig.java:[37,52] package org.opennms.horizon.flows.classification.csv does not exist
[ERROR] /Users/cle/dev/horizon-stream/metrics-processor/main/src/main/java/org/opennms/horizon/flows/FlowsApplicationConfig.java:[38,57] package org.opennms.horizon.flows.classification.internal does not exist
[ERROR] /Users/cle/dev/horizon-stream/metrics-processor/main/src/main/java/org/opennms/horizon/flows/FlowsApplicationConfig.java:[39,45] package org.opennms.horizon.flows.grpc.client does not exist
[ERROR] /Users/cle/dev/horizon-stream/metrics-processor/main/src/main/java/org/opennms/horizon/flows/FlowsApplicationConfig.java:[40,45] package org.opennms.horizon.flows.integration does not exist
[ERROR] /Users/cle/dev/horizon-stream/metrics-processor/main/src/main/java/org/opennms/horizon/flows/FlowsApplicationConfig.java:[41,45] package org.opennms.horizon.flows.integration does not exist
[ERROR] /Users/cle/dev/horizon-stream/metrics-processor/main/src/main/java/org/opennms/horizon/flows/FlowsApplicationConfig.java:[42,44] package org.opennms.horizon.flows.processing does not exist
[ERROR] /Users/cle/dev/horizon-stream/metrics-processor/main/src/main/java/org/opennms/horizon/flows/FlowsApplicationConfig.java:[43,44] package org.opennms.horizon.flows.processing does not exist
[ERROR] /Users/cle/dev/horizon-stream/metrics-processor/main/src/main/java/org/opennms/horizon/flows/FlowsApplicationConfig.java:[44,44] package org.opennms.horizon.flows.processing does not exist
[ERROR] /Users/cle/dev/horizon-stream/metrics-processor/main/src/main/java/org/opennms/horizon/flows/FlowsApplicationConfig.java:[86,12] cannot find symbol
[ERROR]   symbol:   class InventoryClient
[ERROR]   location: class org.opennms.horizon.flows.FlowsApplicationConfig
[ERROR] /Users/cle/dev/horizon-stream/metrics-processor/main/src/main/java/org/opennms/horizon/flows/FlowsApplicationConfig.java:[91,79] cannot find symbol
[ERROR]   symbol:   class DocumentEnricherImpl
[ERROR]   location: class org.opennms.horizon.flows.FlowsApplicationConfig
[ERROR] /Users/cle/dev/horizon-stream/metrics-processor/main/src/main/java/org/opennms/horizon/flows/FlowsApplicationConfig.java:[92,42] cannot find symbol
[ERROR]   symbol:   class FlowRepository
[ERROR]   location: class org.opennms.horizon.flows.FlowsApplicationConfig
[ERROR] /Users/cle/dev/horizon-stream/metrics-processor/main/src/main/java/org/opennms/horizon/flows/FlowsApplicationConfig.java:[91,12] cannot find symbol
[ERROR]   symbol:   class Pipeline
[ERROR]   location: class org.opennms.horizon.flows.FlowsApplicationConfig
[ERROR] /Users/cle/dev/horizon-stream/metrics-processor/main/src/main/java/org/opennms/horizon/flows/FlowsApplicationConfig.java:[101,12] cannot find symbol
[ERROR]   symbol:   class FlowRepository
[ERROR]   location: class org.opennms.horizon.flows.FlowsApplicationConfig
[ERROR] /Users/cle/dev/horizon-stream/metrics-processor/main/src/main/java/org/opennms/horizon/flows/FlowsApplicationConfig.java:[106,12] cannot find symbol
[ERROR]   symbol:   class ClassificationEngine
[ERROR]   location: class org.opennms.horizon.flows.FlowsApplicationConfig
[ERROR] /Users/cle/dev/horizon-stream/metrics-processor/main/src/main/java/org/opennms/horizon/flows/FlowsApplicationConfig.java:[118,62] cannot find symbol
[ERROR]   symbol:   class InventoryClient
[ERROR]   location: class org.opennms.horizon.flows.FlowsApplicationConfig
[ERROR] /Users/cle/dev/horizon-stream/metrics-processor/main/src/main/java/org/opennms/horizon/flows/FlowsApplicationConfig.java:[119,62] cannot find symbol
[ERROR]   symbol:   class ClassificationEngine
[ERROR]   location: class org.opennms.horizon.flows.FlowsApplicationConfig
[ERROR] /Users/cle/dev/horizon-stream/metrics-processor/main/src/main/java/org/opennms/horizon/flows/FlowsApplicationConfig.java:[117,12] cannot find symbol
[ERROR]   symbol:   class DocumentEnricherImpl
[ERROR]   location: class org.opennms.horizon.flows.FlowsApplicationConfig
[ERROR] /Users/cle/dev/horizon-stream/metrics-processor/main/src/main/java/org/opennms/horizon/metrics/MetricsProcessorApplication.java:[6,45] package org.opennms.horizon.flows.grpc.client does not exist
[ERROR] /Users/cle/dev/horizon-stream/metrics-processor/main/src/main/java/org/opennms/horizon/flows/FlowProcessor.java:[33,47] package org.opennms.dataplatform.flows.document does not exist
[ERROR] /Users/cle/dev/horizon-stream/metrics-processor/main/src/main/java/org/opennms/horizon/flows/FlowProcessor.java:[34,44] package org.opennms.horizon.flows.processing does not exist
[ERROR] /Users/cle/dev/horizon-stream/metrics-processor/main/src/main/java/org/opennms/horizon/flows/FlowProcessor.java:[51,13] cannot find symbol
[ERROR]   symbol:   class Pipeline
[ERROR]   location: class org.opennms.horizon.flows.FlowProcessor
[ERROR] /Users/cle/dev/horizon-stream/metrics-processor/main/src/main/java/org/opennms/horizon/flows/FlowProcessor.java:[53,32] cannot find symbol
[ERROR]   symbol:   class Pipeline
[ERROR]   location: class org.opennms.horizon.flows.FlowProcessor
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
mvn clean package jib:dockerBuild -Dapplication.docker.image=$EXPECTED_REF -f metrics-processor -Djib.from.platforms=linux/$(tilt get cluster default -o=jsonpath --template="{.status.arch}") -pl main exited with exit code 1

Build Failed: Custom build "mvn clean package jib:dockerBuild -Dapplication.docker.image=$EXPECTED_REF -f metrics-processor -Djib.from.platforms=linux/$(tilt get cluster default -o=jsonpath --template=\"{.status.arch}\") -pl main" failed: exit status 1
█`

2023-03-01 18:28 UTC, geraldhumphries approved these changes
LGTM and works for me. Will get someone else to test it locally before we merge, but the builds seem to be much more stable now.

2023-03-03 21:44 UTC, artnaseef commented on Tiltfile
> +        'mvn clean package jib:dockerBuild -DskipTests -Dapplication.docker.image=$EXPECTED_REF -f {} -Djib.from.platforms=linux/{} {}'.format(base_path, cluster_arch_cmd, submodule_flag),
Avoiding calls to specific maven plugins from the cli, and capturing the specifics needed to acheive a specific build result in the POM files, will make the builds easier to maintain and use.

With that said, recent changes should eliminate the need to use `jib:dockerBuild` explicitly on the command-line.  However we may need to use `mvn install` instead of `mvn package`

2023-03-04 16:46 UTC, cgorantla approved these changes
LGTM!

2023-03-06 13:55 UTC, merged