HS-951 Make Adapter functional
OpenNMS-Cloud/horizon-stream pull request #726
Opened 2023-02-10 13:43 UTC by FrancescoBuc86

https://opennms.atlassian.net/browse/HS-951

2023-02-10 13:43 UTC, FrancescoBuc86 commented
Tests to be added, on it right now

2023-02-14 16:02 UTC, fooker requested changes
Having adapters here does not make any sense. They just add another layer of complexity without adding any functionality at all.

2023-02-14 16:19 UTC, FrancescoBuc86 commented
> Having adapters here does not make any sense. They just add another layer of complexity without adding any functionality at all.

Hi Dustin, can you explain what do you mean by "here"?

2023-02-14 16:21 UTC, freddy61025 requested changes
Two more questions.
1. Have you tried to turn on tilt and monitor Kafka results?
2. Have you copied all adapter related test?

2023-02-14 16:21 UTC, freddy61025 commented on minion/minion-grpc/grpc-features/src/main/feature/feature.xml
> +           <bundle>mvn:com.google.guava/guava/${guava.version}</bundle>
it is already in internal-grpc-guava.

2023-02-14 16:21 UTC, freddy61025 commented on minion/minion-grpc/grpc-features/src/main/feature/feature.xml
> +           <bundle>wrap:mvn:com.google.protobuf/protobuf-java/${protobuf.version}</bundle>
it is in grpc-protobuf, seems duplicated.

2023-02-14 16:21 UTC, freddy61025 commented on shared-lib/horizon-ipc/ipc-grpc/ipc-grpc-contract/pom.xml
> +        <dependency>
why we need to modify shared-lib?

2023-02-14 16:21 UTC, freddy61025 commented on minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/adapter/common/AbstractFlowAdapter.java
> +        LOG.debug("Completed Adapter and Enrichment step for {} telemetry message.", telemetryMessage);
Is this message accurate? Enrichment is not done at here right?

2023-02-14 16:21 UTC, freddy61025 commented on minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/adapter/common/AbstractFlowAdapter.java
> +    protected abstract P parse(TelemetryMessage message);
It is better to leave comment about what is that function about.

2023-02-14 16:21 UTC, freddy61025 commented on minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/adapter/common/AbstractFlowAdapter.java
> +    protected abstract List<Flow> convert(final P packet, final Instant receivedAt);
It is better to leave comment about what is that function about.

2023-02-15 09:37 UTC, FrancescoBuc86 commented on minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/parser/ParserBase.java
> +import static java.util.Objects.nonNull;
ok

2023-02-15 09:38 UTC, FrancescoBuc86 commented on minion/minion-flows/flows-parser/src/test/java/org/opennms/horizon/minion/flows/parser/AdapterHolderTest.java
> +import static org.junit.Assert.*;
ok

2023-02-16 21:13 UTC, closed without merging