HS-926: Integration between metric processor and inventory services
OpenNMS-Cloud/horizon-stream pull request #736
Opened 2023-02-13 23:52 UTC by freddy61025

## Description

## Jira link(s)
- https://opennms.atlassian.net/browse/HS-926?focusedCommentId=70738

## Flagged for review

## Checklist
* [x] Follows Horizon Stream's [development guidelines.](https://github.com/OpenNMS/horizon-stream/wiki/Development-Guidelines)
* [x] Appropriate reviewer(s) have been selected.
* [x] Jira issue(s) have been updated to "In Review".
* [x] Includes [appropriate tests.](https://github.com/OpenNMS/horizon-stream/wiki/Test-Strategy)
* [x] Documentation has been updated as necessary.

2023-02-20 14:36 UTC, FrancescoBuc86 commented on metrics-processor/flows/src/test/java/org/opennms/horizon/flows/classification/csv/CsvServiceTest.java
> +//        FilterService filterService = new CachingFilterService();
This can probably be removed?

2023-02-20 14:38 UTC, FrancescoBuc86 commented on metrics-processor/flows/src/test/java/org/opennms/horizon/flows/classification/value/RangedValueTest.java
> +    @Test
Space missing

2023-02-20 14:50 UTC, FrancescoBuc86 requested changes

2023-02-20 14:50 UTC, FrancescoBuc86 commented on metrics-processor/flows/src/test/java/org/opennms/horizon/flows/processing/MockDocumentEnricherFactory.java
> +
these comments can be removed?

2023-02-20 14:50 UTC, FrancescoBuc86 commented on metrics-processor/flows/src/test/java/org/opennms/horizon/flows/processing/MockDocumentEnricherFactory.java
> +    private final DocumentEnricherImpl enricher;
same here

2023-02-20 14:50 UTC, FrancescoBuc86 commented on metrics-processor/flows/src/test/java/org/opennms/horizon/flows/processing/MockDocumentEnricherFactory.java
> +    }
same

2023-02-20 14:50 UTC, FrancescoBuc86 commented on metrics-processor/flows/src/test/java/org/opennms/horizon/flows/processing/MockDocumentEnricherFactory.java
> +}
same here

2023-02-20 14:50 UTC, FrancescoBuc86 commented on metrics-processor/main/src/main/java/org/opennms/horizon/metrics/MetricsProcessorApplication.java
> +    }
why defining these beans here instead of in the FlowsApplicationConfig.java?

2023-02-20 22:20 UTC, freddy61025 commented on metrics-processor/main/src/main/java/org/opennms/horizon/metrics/MetricsProcessorApplication.java
> +    }
moved

2023-02-20 22:20 UTC, freddy61025 commented on metrics-processor/flows/src/test/java/org/opennms/horizon/flows/processing/MockDocumentEnricherFactory.java
> +}
removed

2023-02-20 22:20 UTC, freddy61025 commented on metrics-processor/flows/src/test/java/org/opennms/horizon/flows/processing/MockDocumentEnricherFactory.java
> +    }
removed

2023-02-20 22:20 UTC, freddy61025 commented on metrics-processor/flows/src/test/java/org/opennms/horizon/flows/processing/MockDocumentEnricherFactory.java
> +    private final DocumentEnricherImpl enricher;
removed

2023-02-20 22:20 UTC, freddy61025 commented on metrics-processor/flows/src/test/java/org/opennms/horizon/flows/processing/MockDocumentEnricherFactory.java
> +
removed

2023-02-20 22:20 UTC, freddy61025 commented on metrics-processor/flows/src/test/java/org/opennms/horizon/flows/classification/value/RangedValueTest.java
> +    @Test
fixed

2023-02-20 22:21 UTC, freddy61025 commented on metrics-processor/flows/src/test/java/org/opennms/horizon/flows/classification/csv/CsvServiceTest.java
> +//        FilterService filterService = new CachingFilterService();
removed

2023-02-21 12:08 UTC, FrancescoBuc86 approved these changes

2023-02-24 21:44 UTC, fooker requested changes

2023-02-24 21:44 UTC, fooker commented on metrics-processor/flows/src/main/java/org/opennms/horizon/flows/integration/FlowRepositoryImpl.java
> +    private static final Logger LOG = LoggerFactory.getLogger(PipelineImpl.class);
Wrong logger class.

2023-02-24 21:44 UTC, fooker commented on metrics-processor/flows/src/main/java/org/opennms/horizon/flows/processing/DocumentEnricherImpl.java
> +
```suggestion

            document.setTenantId(tenantId);
```

2023-02-24 21:45 UTC, fooker requested changes

2023-02-24 21:45 UTC, fooker commented on metrics-processor/flows/src/main/java/org/opennms/horizon/flows/processing/DocumentEnricherImpl.java
> +    private static final String NODE_METADATA_CACHE = "flows.node.metadata";
Unused

2023-02-24 21:54 UTC, freddy61025 commented on metrics-processor/flows/src/main/java/org/opennms/horizon/flows/integration/FlowRepositoryImpl.java
> +    private static final Logger LOG = LoggerFactory.getLogger(PipelineImpl.class);
fixed

2023-02-24 21:54 UTC, freddy61025 commented on metrics-processor/flows/src/main/java/org/opennms/horizon/flows/processing/DocumentEnricherImpl.java
> +
added

2023-02-24 21:55 UTC, fooker approved these changes

2023-02-24 23:29 UTC, merged