HS-951 Adding Adapter Step without Adapter module
OpenNMS-Cloud/horizon-stream pull request #747
Opened 2023-02-16 15:09 UTC by FrancescoBuc86

https://opennms.atlassian.net/browse/HS-951

2023-02-16 16:13 UTC, freddy61025 requested changes
there still have one test fail.

2023-02-16 16:13 UTC, freddy61025 commented on minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/parser/TelemetryRegistryImpl.java
>              if (factory.getClass().getName().contains(listenerConfig.getClassName())) {
if you use full class path in config. Then you may need factory.getListenerClass().getName().equals(listenerConfig.getClassName()). 

Also same for parser.

2023-02-16 18:16 UTC, FrancescoBuc86 commented
> there still have one test fail.

Yes saw that, I'll take care of it

2023-02-17 14:09 UTC, freddy61025 approved these changes
LGTM

2023-02-17 14:11 UTC, merged