HS-1012 Fixed the IpInterface and SnmpInterface schema and data model
OpenNMS-Cloud/horizon-stream pull request #762
Opened 2023-02-17 21:33 UTC by yangli2014

## Description

Updated the schema and data model, the node scan result data model, the scan process, and the results process.
## Jira link(s)
- https://issues.opennms.org/browse/HS-1012

## Flagged for review

## Checklist
* [ ] Follows Horizon Stream's [development guidelines.](https://github.com/OpenNMS/horizon-stream/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS/horizon-stream/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.

2023-02-20 11:19 UTC, james8hut requested changes
Please rebase on develop

2023-02-20 11:19 UTC, james8hut commented on inventory/src/test/java/org/opennms/horizon/inventory/repository/IpInterfaceRepositoryTest.java
> +        nodeRepository.deleteAll();
Tenancy has changed due to HS-1013.
Without code like the below, nothing will be deleted:
        Context.current().withValue(GrpcConstants.TENANT_ID_CONTEXT_KEY, tenantId).run(()->
        {
            nodeRepository.deleteAll();
        });

2023-02-20 11:19 UTC, james8hut commented on inventory/src/test/java/org/opennms/horizon/inventory/repository/IpInterfaceRepositoryTest.java
> +        snmpInterfaceRepository.save(snmpInterface);
Similarily here:
In this case, you'll get an error about the tenantId being different to the one it is trying to save.
Best to wrap the entire method with the code above

2023-02-20 11:19 UTC, james8hut commented on inventory/src/test/java/org/opennms/horizon/inventory/repository/IpInterfaceRepositoryTest.java
> +        var result2 = ipInterfaceRepository.findById(ipInterface.getId());
Here, without the new code, findById won't get anything back. (Essentially, this is the case where a different tenant calls findById with somebody elses id.)

2023-02-20 11:19 UTC, james8hut commented on inventory/src/test/java/org/opennms/horizon/inventory/repository/IpInterfaceRepositoryTest.java
> +        int ifIndex = 10;
similar

2023-02-21 14:45 UTC, yangli2014 commented on inventory/src/test/java/org/opennms/horizon/inventory/repository/IpInterfaceRepositoryTest.java
> +        nodeRepository.deleteAll();
updated

2023-02-21 16:43 UTC, james8hut commented on shared-lib/protobuf/src/main/proto/nodescan.proto
> +/*message IpTableScanResult {
Query: Should this be removed rather than commented out?

2023-02-21 16:43 UTC, james8hut approved these changes

2023-02-21 18:38 UTC, merged