HS-925 Send FlowDocuments to Flow Ingestor through GRPC
OpenNMS-Cloud/horizon-stream pull request #771
Opened 2023-02-21 16:11 UTC by FrancescoBuc86

https://opennms.atlassian.net/browse/HS-925

2023-02-28 13:18 UTC, j-white commented on metrics-processor/flows/src/main/java/org/opennms/horizon/flows/grpc/client/IngestorClient.java
> +            LOG.error("Failed to send StoreFlowDocumentRequest to FlowIngestor. ", e);
include the tenantId in the log message

2023-02-28 13:18 UTC, j-white commented on metrics-processor/main/src/main/resources/application.yml
> +    ingestor: flows.onms-dp-dev.dev.nonprod.dataservice.opennms.com:443
need some more thought on this one

2023-02-28 13:18 UTC, j-white commented on metrics-processor/main/src/test/resources/test-application.yml
> +    ingestor: flows.onms-dp-dev.dev.nonprod.dataservice.opennms.com:443
similarly here

2023-02-28 13:18 UTC, j-white commented on parent-pom/pom.xml
> +        <flows.gateway.grpc.version>1.3.2-feature-DC-523-16</flows.gateway.grpc.version>
would be nice to point to artifacts release from the `main` branch

2023-02-28 13:56 UTC, FrancescoBuc86 commented on metrics-processor/flows/src/main/java/org/opennms/horizon/flows/grpc/client/IngestorClient.java
> +            LOG.error("Failed to send StoreFlowDocumentRequest to FlowIngestor. ", e);
sure

2023-02-28 14:39 UTC, freddy61025 requested changes
some minor issues.

2023-02-28 14:39 UTC, freddy61025 commented on metrics-processor/main/src/main/resources/application.yml
> +    inventory: localhost:29065
are you sure this will work in tilt ?

2023-02-28 14:39 UTC, freddy61025 commented on metrics-processor/main/src/main/resources/application.yml
> +    retry:
this block better move under ingestor.

2023-02-28 14:39 UTC, freddy61025 commented on metrics-processor/main/src/test/java/org/opennms/horizon/flows/grpc/client/IngestorClientTest.java
> +@TestPropertySource(locations = "classpath:test-application.yml")
How difficult to mock the grpc server? For unit test, it is better to not rely on external resources.

2023-02-28 14:39 UTC, freddy61025 commented on metrics-processor/flows/src/main/java/org/opennms/horizon/flows/processing/PipelineImpl.java
> +        public void persist(final Collection<FlowDocument> flows, String tenantId) throws FlowException {
There should have tenantId in the FlowDocument already.

2023-02-28 14:39 UTC, freddy61025 commented on metrics-processor/flows/src/main/java/org/opennms/horizon/flows/grpc/client/IngestorClient.java
> +                LOG.info("Attempt number {} to persist StoreFlowDocumentRequest for tenantId {}. ", tenantId, context.getRetryCount() + 1);
It should be debug or trace.

2023-02-28 14:39 UTC, freddy61025 commented on metrics-processor/main/src/main/java/org/opennms/horizon/flows/FlowsApplicationConfig.java
> +            .sslContext(GrpcSslContexts.forClient().trustManager(InsecureTrustManagerFactory.INSTANCE).build())
add
.maxInboundMessageSize()
.maxInboundMetadataSize()
and make sure it align with the server.

2023-02-28 14:46 UTC, fooker requested changes

2023-02-28 14:46 UTC, fooker commented on metrics-processor/flows/src/main/java/org/opennms/horizon/flows/integration/FlowRepositoryImpl.java
> +            LOG.info("No EnrichedFlow present, skipping flow data persisting step. ");
This should be `LOG.trace`.

2023-02-28 14:50 UTC, FrancescoBuc86 commented on metrics-processor/main/src/main/resources/application.yml
> +    inventory: localhost:29065
nope, restoring the previous one instead

2023-02-28 15:05 UTC, FrancescoBuc86 commented on metrics-processor/main/src/test/java/org/opennms/horizon/flows/grpc/client/IngestorClientTest.java
> +@TestPropertySource(locations = "classpath:test-application.yml")
Good point, I can have a look into it

2023-02-28 15:11 UTC, FrancescoBuc86 commented on metrics-processor/flows/src/main/java/org/opennms/horizon/flows/processing/PipelineImpl.java
> +        public void persist(final Collection<FlowDocument> flows, String tenantId) throws FlowException {
you're right

2023-02-28 15:48 UTC, FrancescoBuc86 commented on metrics-processor/flows/src/main/java/org/opennms/horizon/flows/grpc/client/IngestorClient.java
> +                LOG.info("Attempt number {} to persist StoreFlowDocumentRequest for tenantId {}. ", tenantId, context.getRetryCount() + 1);
it makes sense

2023-02-28 15:52 UTC, FrancescoBuc86 commented on metrics-processor/main/src/main/java/org/opennms/horizon/flows/FlowsApplicationConfig.java
> +            .sslContext(GrpcSslContexts.forClient().trustManager(InsecureTrustManagerFactory.INSTANCE).build())
well these values are not set on the server side

2023-02-28 16:07 UTC, FrancescoBuc86 commented on metrics-processor/main/src/main/resources/application.yml
> +    ingestor: flows.onms-dp-dev.dev.nonprod.dataservice.opennms.com:443
I just reverted it to     inventory: opennms-inventory:6565
I hope this is what you meant..?

2023-03-02 15:05 UTC, freddy61025 commented on parent-pom/pom.xml
> +        <flows.gateway.grpc.version>1.3.2-feature-DC-523-16</flows.gateway.grpc.version>
There is no main version in dataplatform yet. However, we could follow cloud plugin use "LATEST" before final release version is fixed.

2023-03-02 15:20 UTC, FrancescoBuc86 commented on metrics-processor/main/src/test/resources/test-application.yml
> +spring:
actually not

2023-03-02 15:45 UTC, FrancescoBuc86 commented on parent-pom/pom.xml
> +        <flows.gateway.grpc.version>1.3.2-feature-DC-523-16</flows.gateway.grpc.version>
ok, set it to LATEST

2023-03-02 18:34 UTC, freddy61025 commented on metrics-processor/main/src/main/resources/application.yml
> +    ingestor: flows.onms-dp-dev.dev.nonprod.dataservice.opennms.com:443
@FrancescoBuc86 There is two minor changes. 

- name it more specific e.g. flow-ingestor
- add comment about the url it is temporary use

2023-03-02 18:49 UTC, FrancescoBuc86 commented on metrics-processor/main/src/main/resources/application.yml
> +    ingestor: flows.onms-dp-dev.dev.nonprod.dataservice.opennms.com:443
done

2023-03-02 18:54 UTC, freddy61025 approved these changes
LGTM

2023-03-02 19:08 UTC, merged