HS-1111: MP Alert Conditions
OpenNMS-Cloud/horizon-stream pull request #912
Opened 2023-03-24 16:04 UTC by mikewrosey

## Description
Handles alert conditions for both threshold and events

## Jira link(s)
- https://issues.opennms.org/browse/HS-1111

## Checklist
* [ ] Follows Horizon Stream's [development guidelines.](https://github.com/OpenNMS/horizon-stream/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS/horizon-stream/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.
* [ ] Notify devops of changes to the Charts

2023-03-26 20:55 UTC, chinh-cle requested changes

2023-03-26 20:55 UTC, chinh-cle commented on ui/src/components/MonitoringPolicies/MonitoringPoliciesCard.vue
>            v-for="(condition, index) in rule.conditions"
missing `key` binding attribute

2023-03-26 20:55 UTC, chinh-cle commented on ui/src/components/MonitoringPolicies/MonitoringPoliciesPolicyForm.vue
> +          v-for="(policy, index) in store.monitoringPolicies"
missing key binding attribute

2023-03-26 20:55 UTC, chinh-cle commented on ui/src/components/MonitoringPolicies/MonitoringPoliciesRuleForm.vue
> +              v-for="(cond, index) in store.selectedRule!.conditions"
I think it's not recommended to have v-if and v-for in same element

2023-03-26 20:55 UTC, chinh-cle commented on ui/src/components/MonitoringPolicies/MonitoringPoliciesRuleForm.vue
> +              :condition="(cond as ThresholdCondition)"
missing :key attribute for v-for

2023-03-26 20:55 UTC, chinh-cle commented on ui/src/components/MonitoringPolicies/MonitoringPoliciesRuleForm.vue
> +              :index="index"
same comment as above

2023-03-27 02:03 UTC, mikewrosey commented on ui/src/components/MonitoringPolicies/MonitoringPoliciesPolicyForm.vue
> +          v-for="(policy, index) in store.monitoringPolicies"
done!

2023-03-27 02:03 UTC, mikewrosey commented on ui/src/components/MonitoringPolicies/MonitoringPoliciesRuleForm.vue
> +              v-for="(cond, index) in store.selectedRule!.conditions"
you're right, wrapped them in template elements

2023-03-27 08:01 UTC, chinh-cle approved these changes
LGTM

2023-03-27 14:16 UTC, merged